@startuml
top to bottom direction
component "Embedded" as Embedded {
    component "Camera" as Camera
    component "Parking Gate Device" as ParkingGateDevice {
        component "Ultrasonic sensor" as UltrasonicSensor
    }
    component "Parking Slot Sensor" as ParkingSlotSensor
    component "Parking Card Reader" as ParkingCardReader
}

component "Server" as Server {
    component "Controller" as ControllerServer {
        component "Embedded Adapter" as EmbeddedAdapter 
        ' May need to rename ---v
        component "Web Adapter" as WebAdapter
    }
    component "Service" as Service {
        ' component "Embedded Handler Service" as EmbeddedHandlerService
        component "Authentication Service" as AuthenticationService
        component "Parking Suggestion Service" as ParkingSuggestionService
        component "Paking Cards' Status Service" as ParkingCardsStatusService
        component "Parking Slot Service" as ParkingSlotService
        component "Statistics Service" as StatisticsService
    }
    component "Repository" as Repository {
        component "Authentication Repository" as AuthenticationRepository
        component "Parking Daily Traffic Repository" as ParkingLotDailyTrafficRepository
        component "Parking Lot Status Repository" as ParkingLotStatusRepository
        component "Parking Cards Repository" as ParkingCardsRepository
    }
    ParkingSuggestionService <--> ParkingLotStatusRepository
    ParkingSlotService <--> ParkingLotStatusRepository
    ParkingCardsStatusService <--> ParkingCardsRepository
    StatisticsService <--> ParkingLotDailyTrafficRepository

    component "Database" as Database

    ControllerServer <--> Service
    Repository <--> Database
    Embedded --> EmbeddedAdapter: "MQTT/HTTP(s)"
}

component "Client" as Client {
    component "Controller" as ControllerClient
    component "View" as View {
        component "Map View" as MapView {
            component "Parking Slots' Status" as ParkingSlotsStatusView
            component "Parking Suggestions" as ParkingSuggestionsView
        }
        component "Traffic Dashboard" as TrafficDashboard
        component "Authentication View" as AuthenticationView
    }
    component "Model" as ModelClient {
        component "Parking Slots Status Model" as ParkingSlotsStatusModel
        component "Parking Suggestions Model" as ParkingSuggestionsModel
        component "Traffic Statistics Model" as TrafficStatisticsModel
        component "Authentication Model" as AuthenticationModel
    }
    ParkingSlotsStatusModel --> ParkingSlotsStatusView
    ParkingSuggestionsModel --> ParkingSuggestionsView
    TrafficStatisticsModel --> TrafficDashboard
    AuthenticationModel --> AuthenticationView
}   
ControllerClient <--> WebAdapter: "WebSocket/WebTransport"
View --> ControllerClient: "send input"
ControllerClient --> View: "update view"
ControllerClient --> ModelClient: "manipulate data"


@enduml

